autotools/autoconf-2.69.tar.xz:
  size: 1214744
  object_id: 1e3e3c95-d525-4f96-943d-5da1511e0bda
  sha: e891c3193029775e83e0534ac0ee0c4c711f6d23
erlang/OTP-17.5.6.9.tar.gz:
  size: 33130949
  object_id: 0ad6395d-42c9-4bed-7356-4f2858184b4a
  sha: a31210e750636527515d208472b68beb6641ee6b
erlang/OTP-18.3.4.9.tar.gz:
  size: 33674233
  object_id: c74870ab-3dcd-4f12-6638-ee9281f9d42f
  sha: ab09659d80525d7eac6741289d777a39f295d2dc
erlang/OTP-19.3.6.10.tar.gz:
  size: 34002999
  object_id: 7b2a7a3e-66b6-4234-62d9-68088498f9c8
  sha: ab7bf769245dfc89b2ae94e9c081a0eb32f83e5f
erlang/OTP-20.3.8.7.tar.gz:
  size: 53508218
  object_id: efa65cfc-90d4-4f45-73ea-6ba27001d211
  sha: 9e99068fa33594865e8c9f787a30392253cdc230
erlang/OTP-20.3.8.8.tar.gz:
  size: 53510573
  object_id: 2e2aff6f-3251-4e7c-6531-f73f131e9b5e
  sha: 570e19865d61215b406bb39eb78346f59cd2c1a9
erlang/OTP-21.0.6.tar.gz:
  size: 52839933
  object_id: dcd7e8e9-b307-4bfa-56a8-e9c89c5671c9
  sha: 030795055e74a445f830ab99aba5c317dbd46cb0
erlang/OTP-R16B03-1.tar.gz:
  size: 32821912
  object_id: e9af9f9a-ce56-4623-63da-227843523655
  sha: a52b93ce3faa4be148b0b5b2f4fc51093f0813bc
java/jre-8u181-linux-x64.tar.gz:
  size: 81191893
  object_id: b838ee6d-f735-4c3f-70de-1a450b40d8dc
  sha: c7e8984aa2a0a4119908d112427876415f3ddbbc
observer_cli-1.2.1.tar.gz:
  size: 700973
  object_id: a7ced4ec-5aeb-4a51-450b-63a68b61e8e4
  sha: 688b340abc67ddc1b27ff1f224978896c8c6d6f3
rabbitmq-perf-test-2.2.0.RC1-bin.tar.gz:
  size: 4762833
  object_id: 121b5265-e245-45ae-6e74-1dd95ed82e57
  sha: ab27ac3c30e9a525a457c010e44c853f4881fea2
rabbitmq-plugins/3.6/accept-0.3.3.ez:
  size: 13625
  object_id: 7cf850e3-ad75-4cdb-487e-11c484765e2a
  sha: c4cfeb96ed383eb7eecbb48b4ca8266a77343d76
rabbitmq-plugins/3.6/prometheus-3.4.0.ez:
  size: 207436
  object_id: 47cc78de-ef0f-4aa2-77b3-da961f67cf92
  sha: 5fb43c43d177e99a24d96f85c782cbdfce32bd8a
rabbitmq-plugins/3.6/prometheus_httpd-2.1.4.ez:
  size: 17065
  object_id: 46a8eba1-f1ad-4852-4d89-f5f02baaa30f
  sha: 6e7c68a02d27827735b1f6ac28e093fa5f9b5700
rabbitmq-plugins/3.6/prometheus_rabbitmq_exporter-v3.6.12.1.ez:
  size: 199139
  object_id: bd2541ad-4f42-4aa7-6f35-7573c40fe95a
  sha: d5de2fe7640426cfc1ae9721a9a241515e05575b
rabbitmq-plugins/3.6/rabbitmq_random_exchange-0.10.0.ez:
  size: 5489
  object_id: e2637139-ead3-4855-5990-c94fd53466b3
  sha: d349388df63a36332a7e616656332f7169792964
rabbitmq-plugins/3.7/accept-0.3.3.ez:
  size: 13395
  object_id: e76677c4-b08b-4650-7f44-30b290f80723
  sha: 1d43932039547d458ba13fd1d314028d7cee5936
rabbitmq-plugins/3.7/prometheus-3.4.5.ez:
  size: 198993
  object_id: c100c6ff-6c42-4733-7a4d-a164d3bc0405
  sha: 0ed0deab7227e5a2af5848a1c84bbaebd0292d2f
rabbitmq-plugins/3.7/prometheus_cowboy-0.1.4.ez:
  size: 14344
  object_id: 623ad1b6-8575-484b-61b7-d524b082e17b
  sha: 543c04aae526d653736330f704d2ef4807551e92
rabbitmq-plugins/3.7/prometheus_httpd-2.1.8.ez:
  size: 22055
  object_id: 0ba0cc12-b4ab-4018-7445-1ceaf85e7341
  sha: 681e8d181ea4b032b0bef7ef0125145ce281b12c
rabbitmq-plugins/3.7/prometheus_rabbitmq_exporter-v3.7.2.2.ez:
  size: 215891
  object_id: e368950e-bd10-4ab5-5660-1abd32e2ce93
  sha: d6a817d8bd655b41f73c234262e785af41ed18ee
